### ISSUE TITLE
Linking against Boost on Mac Os X

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/Glimpse#4]
As usual, Mac Os X is a pain and due to incompatibilities between clang and gcc we need to compile our own boost with gcc to make sure the linking works

**Comment by EiffL** [comment]
Added script to build Boost on MacOsX systems in branch #4. Waiting confirmation that compilation is successful on Apple systems

**Comment by olgatihhonova** [comment]
Unfortunately, can't confirm - the same errors persist.

**Comment by EiffL** [comment]
No other  complaints, closing this  issue
