### ISSUE TITLE
Compilation fails on osx

### ISSUE THREAD

**Issue by EiffL** [CosmoStat/Glimpse#9]
@austinpeel ran into issues when compiling glimpse on osx:
```sh
[ 76%] Building CXX object CMakeFiles/glimpse.dir/src/field.cpp.o
In file included from /Users/apeel/Software/glimpse/cosmostat/glimpse/build/extern/include/sparse2d/Memory.h:36:0,
                 from /Users/apeel/Software/glimpse/cosmostat/glimpse/build/extern/include/sparse2d/TempArray.h:20,
                 from /Users/apeel/Software/glimpse/cosmostat/glimpse/build/extern/include/sparse2d/Array.h:20,
                 from /Users/apeel/Software/glimpse/cosmostat/glimpse/build/extern/include/sparse2d/IM_IO.h:24,
                 from /Users/apeel/Software/glimpse/cosmostat/glimpse/src/field.cpp:44:
/Users/apeel/Software/glimpse/cosmostat/glimpse/build/extern/include/sparse2d/GlobalInc.h:30:20: fatal error: values.h: No such file or directory
 #include <values.h>
                    ^
compilation terminated.
make[2]: *** [CMakeFiles/glimpse.dir/src/field.cpp.o] Error 1
make[1]: *** [CMakeFiles/glimpse.dir/all] Error 2
make: *** [all] Error 2
```

Looks like a particular flag for osx is missing somewhere in cmake. @sfarrens thoughts ?
I'll had a travis CI osx target to test against this.

**Comment by giordano** [comment]
There is no `values.h` on OS X.  On GNU/Linux the file `values.h` itself says:

> ```
> /* This interface is obsolete.  New programs should use
>    <limits.h> and/or <float.h> instead of <values.h>.  */
> ```

This file should not be included at all.

**Comment by EiffL** [comment]
@giordano  So, do you think it should build without issues on osx?

Oups, yes,sorry forgot what the issue actually was, it depends on whether sparse2d has been updated  or not. @sfarrens  would know.

**Comment by giordano** [comment]
This should be fixed by https://github.com/CosmoStat/Sparse2D/pull/19
